// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GSlate.CodingChallenge.Common.Models.Entity
{
    public partial class Project
    {
        public Project()
        {
            UserProjects = new HashSet<UserProject>();
        }

        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndTime { get; set; }

        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}