// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GSlate.CodingChallenge.Common.Models.Entity
{
    public partial class User
    {
        public User()
        {
            UserProjects = new HashSet<UserProject>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}