// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GSlate.CodingChallenge.Common.Models.Entity
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            UserProjects = new HashSet<UserProject>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}