// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GSlate.CodingChallenge.Common.Models.Entity
{
    [Table("UserProject")]
    public partial class UserProject
    {
        public int UserId { get; set; }
        public int ProjectId { get; set; }
        public bool IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AssignedDate { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("UserProjects")]
        public virtual Project Project { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("UserProjects")]
        public virtual User User { get; set; }
    }
}